# Generated by Django 4.2.2 on 2023-07-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postDiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titleDate',
            field=models.DateField(auto_now_add=True, verbose_name='작성일'),
        ),
    ]
