# Generated by Django 4.2.2 on 2023-07-06 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postDiary', '0003_rename_body_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='postDiary.post'),
        ),
    ]
