# Generated by Django 4.2.2 on 2023-07-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postDiary', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
